// authenticate
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const CHANGE_NETWORK_STATUS = 'CHANGE_NETWORK_STATUS';

// token
export const UPDATE_HEADERS = 'UPDATE_HEADERS';

// search
export const SEARCH_REPOSITORIES_REQUEST = 'SEARCH_REPOSITORIES_REQUEST';
export const SEARCH_NEXT_REPOSITORIES_REQUEST = 'SEARCH_NEXT_REPOSITORIES_REQUEST';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR';

// modals
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// change search value
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';

// change sort
export const CHANGE_SORT = 'CHANGE_SORT';
